version: '3.7'
services:
  web:
    image: ghcr.io/ob7-ird/observe-logbooks-reader-webapp:main
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./database:/home/app/webapp/database
    ports:
      - "8000:8000"
      