services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
          - type: bind
            source: ./db.sqlite3
            target: /db.sqlite3
    ports:
      - "8000:8000"
