services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - /var/www/lto-webapp/static:/var/www/lto-webapp/static
    depends_on:
      - web
  web:
    image: ghcr.io/ob7-ird/lto-webapp:main
    command: bash -c "python manage.py compilemessages && python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./database:/home/app/webapp/database
      - /var/www/lto-webapp/static:/var/www/lto-webapp/static
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
      
