# Generated by Django 4.2 on 2025-08-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionprofile',
            name='client_app_version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='model_version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='referential_locale',
            field=models.CharField(choices=[('fr_FR', 'Français'), ('en_GB', 'Anglais'), ('es_ES', 'Espagnol')], default='fr_FR', max_length=5),
        ),
    ]
