# Generated by Django 4.2 on 2026-02-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0002_connectionprofile_client_app_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERSConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ers', models.CharField(max_length=128, unique=True)),
                ('database', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('host', models.CharField(max_length=128)),
                ('port', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='ltouser',
            name='ers_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='webapps.ersconnectionprofile'),
        ),
    ]
