site_name: Django webapp documentation
site_url: https://example.com/

plugins:
  - search
  - mkdocstrings

theme:
  name: 'material'
  custom_dir: 'docs'
  palette:
    scheme: default
    primary: blue
  logo: 'assets/images/logo_full.svg'
  favicon: 'assets/images/favicon.svg'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - instant
nav:
  - Home: index.md