"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/

"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DB_DIR = os.path.join(BASE_DIR, "database")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'yvz$wx7h!urn+asjmu$9l56&_d6&7s+y7_9i8+7tsou7cp2xfw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

#SECURE_SSL_REDIRECT=True
# SESSION_COOKIE_SECURE=True
# CSRF_COOKIE_SECURE=True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:8000'
).split(',')

AUTH_USER_MODEL = "webapps.LTOUser"
# AUTH_USER_MODEL = "webapps.User"


TAILWIND_APP_NAME = "theme"
# INTERNAL_IPS = [
#     "127.0.0.1"
# ]

MESSAGE_TAGS = {
    message_constants.SUCCESS: 'success',   # 1
    message_constants.ERROR: 'error',       # 2
    message_constants.WARNING: 'warning',   # 3
    message_constants.INFO: 'info',         # 4
    message_constants.DEBUG: 'debug',       # 5
    6: 'error2',  # Nouveau niveau personnalisé "error2"
}

# Application definition
INSTALLED_APPS = [
#    'daphne',
    'webapps',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'palangre_syc',
]

if DEBUG:
    INSTALLED_APPS += ['django_browser_reload']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    ]

if DEBUG:
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware']

# MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
               'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'webapps.context_processors.global_context', # Ajout du context processor pour la version de l'application
            ],
        },
    },
]

# WSGI_APPLICATION = 'website.wsgi.application'
ASGI_APPLICATION = 'website.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(DB_DIR, "db.sqlite3"),
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGES = [
    ('en', _('English')),
    ('fr', _('Français')),
    # Ajoutez d'autres langues au besoin
] 

LANGUAGE_CODE = 'fr'

LOCALE_PATHS = [
    BASE_DIR / 'locale/',
    # os.path.join(BASE_DIR, 'locale'),
]
# A list of directories where Django looks for translation files

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ── Fichiers statiques ──────────────────────────────────────

STATIC_URL = '/static/'

# STATIC_ROOT : dossier de collecte pour la production
# En dev local, on pointe dans le projet ; en prod Docker, /var/www/...
STATIC_ROOT = os.environ.get(
    'STATIC_ROOT',
    BASE_DIR / 'staticfiles'   # ← dossier local par défaut
)

# STATICFILES_DIRS : dossiers sources supplémentaires
# On n'inclut un chemin que s'il existe réellement
_extra_static = os.environ.get('EXTRA_STATIC_DIR', '')

STATICFILES_DIRS = [
    d for d in [
        BASE_DIR / 'static',
        Path(_extra_static) if _extra_static else None,
    ]
    if d and Path(d).exists()   # ← ignore les chemins inexistants
]



# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'

APP_VERSION = os.environ.get('APP_VERSION', 'dev')